apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-v36
  namespace: argocd
spec:
  source:
    path: manifests
    repoURL: https://github.com/YawarPandar/demo-manifest.git
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: default
  syncPolicy:
    automated:
      prune: true
