apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata: 
  name: app-demo
spec:
  generators:
  - list:
      elements:
      - cluster: dev-app-demo
        url: https://kubernetes.default.svc
      - cluster: prod-demo-demo
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/YawarPandar/demo-manifest.git
        targetRevision: HEAD
        path: appsets-manifests/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true